# Generated by Django 6.0.4 on 2026-04-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text='Например: "img/products/pink_bag.jpg"', max_length=255, verbose_name='Путь к картинке'),
        ),
    ]
